FROM node:20-bookworm-slim

RUN apt update && apt install -y python3 python3-pip python3-setuptools git

RUN pip install awscli aws-sam-cli --upgrade --break-system-packages

WORKDIR /app

CMD [ "bash" ]
