AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pdfgen

  Sample SAM Template for pdfgen

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  Main:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Layers:
        - arn:aws:lambda:ap-northeast-1:764866452798:layer:chrome-aws-lambda:45
        - !Ref FontsLayer
      Events:
        Main:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /main
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - app.ts
  FontsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: fonts_layer
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MainApi:
    Description: 'API Gateway endpoint URL for Prod stage for Main function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/main/'
  Main:
    Description: 'Main Lambda Function ARN'
    Value: !GetAtt Main.Arn
  MainIamRole:
    Description: 'Implicit IAM Role created for Main function'
    Value: !GetAtt MainRole.Arn
